server:
  port: 8081
spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3366/springboot-schoolbuilder?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.micro.schoolbuilder.mapper
